# Generated by Django 4.2.16 on 2024-09-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('itemNumber', models.IntegerField()),
                ('archieved', models.BooleanField(default=False)),
            ],
        ),
    ]
