# Generated by Django 4.2.16 on 2024-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_item_description_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No Description')),
                ('price', models.FloatField()),
                ('itemNumber', models.IntegerField()),
                ('archieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
