# Generated by Django 4.2.16 on 2024-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_inventoryitem_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='image',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='imageID',
            field=models.TextField(default='null'),
        ),
    ]
