# Generated by Django 4.2.16 on 2024-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_inventoryimage_remove_inventoryitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='imageID',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(default='null', upload_to='product_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemNumber',
            field=models.IntegerField(default=0),
        ),
    ]
